name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Run-Tests:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go run ./test/cmd/main.go -v ./...